### PR TITLE
Update conda frozen version

### PR DESCRIPTION
**Pull request by RainierBarrett**
Newer frozen miniconda ver and SHA hash! Needs testing to see if it builds still.

### CODE REVIEW

**Comment by RainierBarrett** [comment]
should work now!

**Comment by chrisjonesBSU** [comment]
If we're changing the CUDA version too, then we should double check the other docker files that inherit from this one.  For example, `dockerfile_gpuhoomd3conda` has `ENV CONDA_OVERRIDE_CUDA=10.2`

**Comment by RainierBarrett** [comment]
Do we need specifically CUDA 10.2 for anything? It's not a supported version anymore.

**Comment by erjank** [comment]
We might need to be careful about which cuda version we have in our main
containers such that we can support building hoomd for the older hardware
on Fry and having as best forward compatibility as possible, but I don't
know what the right/best version is without some testing

**Comment by chrisjonesBSU** [comment]
> Do we need specifically CUDA 10.2 for anything? It's not a supported version anymore.

I don't think we need to specify version 10.2, but we should change this line so that it matches the version used in the base container.

**Comment by chrisjonesBSU** [comment]
> We might need to be careful about which cuda version we have in our main
> containers such that we can support building hoomd for the older hardware
> on Fry and having as best forward compatibility as possible, but I don't
> know what the right/best version is without some testing


That's a good point. On Fry, the latest CUDA module we have is 11.7.  Maybe we should stick with that for now instead of 12.1.1

**Comment by RainierBarrett** [comment]
Ah, gotcha, I got a little excited and just grabbed the newest version. I'll revise and re-check builds.

**Comment by RainierBarrett** [comment]
Alright, main two GPU containers build and run OK (make sure you have nvidia runtime docker daemon installed). I'm still working on a HOOMD-TF solution using a different base container so I'm ignoring that and the gputensorflow one for now. Should we update the gpuhoomdconda one as well? (Perhaps rename to gpuhoomd2conda explicitly?)

**Pull request merged**
