### PR TITLE
Add compiled tensorflow to container

### LINKED ISSUE #3: Compile tensorflow in Hoomd-TF container
gpuhoomdtf container should have a from source compilation of tensorflow because I think we are getting some errors due to gcc/cuda version mismatch. 
@RainierBarrett could you post the cudalib errors you were getting?

### PR DESCRIPTION
**Pull request by jennyfothergill**
Compile tensorflow from source according to https://www.tensorflow.org/install/source
fixes #3

### CODE REVIEW

**Comment by jennyfothergill** [comment]
relevant https://github.com/tensorflow/tensorflow/issues/28790

**Comment by jennyfothergill** [comment]
also relevant https://github.com/tensorflow/tensorflow/issues/8527

**Comment by jennyfothergill** [comment]
issue started https://github.com/tensorflow/tensorflow/issues/48380

**Comment by RainierBarrett** [comment]
Just stumbled on this before the meeting, looks like the issue might be related to running in docker?
[This issue](https://github.com/tensorflow/tensorflow/issues/37995) mentions a "patch" for docker rules, found [here](https://github.com/tensorflow/tensorflow/issues/35253#issuecomment-570895670). I'll try poking at these and see what that turns up.

EDIT: This resulted in the same issue with the `no such package '@local_cuda//': The repository '@local_cuda' could not be resolved and referenced by '@cub_archive//:cub'` error.

**Pull request merged**
